### ISSUE TITLE
Awesome package

### ISSUE THREAD

**Issue by alexvicegrab** [moonpyk/dtrx#1]
Would be great to add this to pipy. If you are too busy, I can do it, just let me know.

**Comment by moonpyk** [comment]
Hello, 

I'm not the original author of the package, I've just imported the hg repository here just in case Brett Smith's web site would disappear, so that this piece of gold would not be totally lost.

In my opinion you should try to contact him directly and discuss that with him

Cheers.

**Comment by moonpyk** [comment]
Oh ! @brettcs is among us now, and he imported the repository on github.

https://github.com/brettcs/dtrx
